#!/usr/bin/env node
/**
 * miro-export.js — push a screenshot run to a Miro board via the REST API.
 *   • creates a board
 *   • uploads each screen as an image item (ring layout, hub centered)
 *   • draws a connector from the hub to every other page
 *   • prints the board's shareable viewLink
 *
 * Usage: MIRO_TOKEN=... node miro-export.js <run-folder>
 * Token: create a Miro app (https://miro.com/app/settings/user-profile/apps),
 *        give it `boards:write`, copy the OAuth access token, then
 *        `export MIRO_TOKEN=...` (never hardcode / never paste in chat).
 *
 * UNTESTED until a real MIRO_TOKEN is available — verify on first run.
 */
const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");

const RUN = process.argv[2];
const TOKEN = process.env.MIRO_TOKEN;
if (!RUN || !fs.existsSync(RUN)) { console.error("usage: MIRO_TOKEN=... node miro-export.js <run-folder>"); process.exit(1); }
if (!TOKEN) {
  console.error("MIRO_TOKEN not set. Create a Miro app with boards:write, then `export MIRO_TOKEN=...`.");
  process.exit(2);
}
const API = "https://api.miro.com/v2";
const H = { Authorization: `Bearer ${TOKEN}` };

const modeDir = ["desktop", "mobile"].map(m => path.join(RUN, m)).find(d => fs.existsSync(d));
if (!modeDir) { console.error("no desktop/mobile folder in run"); process.exit(1); }
const pngs = fs.readdirSync(modeDir).filter(f => /\.png$/i.test(f)).sort();
if (!pngs.length) { console.error("no pngs"); process.exit(1); }
const labelOf = f => f.replace(/^\d+[-_]/, "").replace(/\.png$/i, "").replace(/[-_]+/g, " ").trim().toUpperCase() || f;

// ring layout in Miro center-origin coords (hub at 0,0; y grows downward)
const N = pngs.length, RATIO = 9 / 16, W = 320, HUBW = 440;
const R = Math.max(520, Math.round((N * 360) / (2 * Math.PI)));
const nodes = pngs.map((f, i) => {
  if (i === 0) return { f, label: labelOf(f), x: 0, y: 0, w: HUBW, hub: true };
  const k = i - 1, ang = (k / (N - 1)) * Math.PI * 2 - Math.PI / 2;
  return { f, label: labelOf(f), x: Math.round(R * Math.cos(ang)), y: Math.round(R * Math.sin(ang)), w: W };
});

const sleep = ms => new Promise(r => setTimeout(r, ms));

async function main() {
  // 1) create board
  const appName = path.basename(RUN).replace(/\..*$/, "");
  const cb = await fetch(`${API}/boards`, {
    method: "POST", headers: { ...H, "Content-Type": "application/json" },
    body: JSON.stringify({ name: `${appName} — UI MAP`, description: "Auto-generated by /show-ui" }),
  });
  if (!cb.ok) { console.error("create board failed:", cb.status, await cb.text()); process.exit(1); }
  const board = await cb.json();
  console.log("board:", board.id, board.viewLink);

  // 2) upload images (resized) → item ids
  const TMP = fs.mkdtempSync("/tmp/miro-");
  const ids = {};
  for (const n of nodes) {
    const out = path.join(TMP, n.f);
    try { execSync(`sips --resampleWidth 900 ${JSON.stringify(path.join(modeDir, n.f))} --out ${JSON.stringify(out)}`, { stdio: "ignore" }); }
    catch { fs.copyFileSync(path.join(modeDir, n.f), out); }
    const form = new FormData();
    form.append("resource", new Blob([fs.readFileSync(out)], { type: "image/png" }), n.f);
    form.append("data", JSON.stringify({ title: n.label, position: { x: n.x, y: n.y }, geometry: { width: n.w } }));
    const r = await fetch(`${API}/boards/${board.id}/images`, { method: "POST", headers: H, body: form });
    if (!r.ok) { console.error(`upload ${n.f} failed:`, r.status, await r.text()); continue; }
    ids[n.f] = (await r.json()).id;
    console.log("uploaded", n.label, "->", ids[n.f]);
    await sleep(250);
  }

  // 3) connectors hub -> each
  const hub = nodes[0];
  for (const n of nodes.slice(1)) {
    if (!ids[hub.f] || !ids[n.f]) continue;
    const r = await fetch(`${API}/boards/${board.id}/connectors`, {
      method: "POST", headers: { ...H, "Content-Type": "application/json" },
      body: JSON.stringify({ startItem: { id: ids[hub.f] }, endItem: { id: ids[n.f] }, shape: "curved", style: { strokeColor: "#c92a2a", strokeWidth: "2" } }),
    });
    if (!r.ok) console.error(`connector ${n.label} failed:`, r.status, await r.text());
    await sleep(200);
  }

  try { fs.rmSync(TMP, { recursive: true, force: true }); } catch {}
  console.log("\nDONE — open:", board.viewLink);
}
main().catch(e => { console.error(e); process.exit(1); });
